In [2]:
import pandas as pd
import math
import numpy as np

In [3]:
#Import set of generated answers for this set of users
df_data = pd.read_csv("SADD_Options_Selected_4users.csv")
print(df_data.sort_values(by="Group") )

df_data_borda = pd.read_csv("SADD_Options_Selected_4users_borda.csv")
df_data_borda.sort_values(by="Group")

   User_ID  Group  P1  P2  P3  P4  P5  P6  P7
0        1      1   1   1   1   1   1   1   1
1        2      1   1   2   1   2   1   2   3
2        3      2   1   3   4   4   4   2   1
3        4      2   1   4   4   4   2   1   4

   User_ID  Group       P1       P2       P3       P4
0        1      1  1;2;3;4  1;2;3;4  1;2;4;3  1;2;4;3
1        2      1  1;2;3;4  2;1;3;4  1;2;3;4  2;4;1;3
2        3      2  1;2;3;4  3;4;1;2  4;2;3;1  4;2;3;1
3        4      2  1;2;3;4  4;1;2;3  4;1;2;3  4;3;2;1

In [4]:
array = df_data_borda.get("P1")[0]
array = array.split(";")
for i in array :
    print(i)

1
2
3
4

In [5]:
#Methods applied to all of these parameters and the option we get at the end

# Majority
# df : dataframe we have with the user/group and parameters we are concerned about
# maj_profile : the profiles we apply majority to
# We could have a separate majority mechanism where we want majority in each of the profiles provided
def majority(df,maj_profile) :
    #create df storing results for each parameter with the option if there was a majority
    df_results = dict.fromkeys(df.columns.copy()[2:])
    df_group = df.query(maj_profile)
    nb_user = df_group["User_ID"].count()
    for parameter in df_results.keys() :
        
       # Retrieve number of votes for each option
        votes = df_group[parameter].value_counts().to_dict()
        temp_arr = []
        
        for key,val in votes.items() :
            if val >= math.ceil(nb_user) / 2 :
                temp_arr.append(key)
        if (len(temp_arr) == 1) :
            print(temp_arr)
            df_results[parameter] = temp_arr[0]
            
    print(df_results)
    
# Unanimity
# df : dataframe we have with the user/group and parameters we are concerned about
# maj_profile : the profiles we apply majority to
def unanimity(df,maj_profile) :
    df_results = dict.fromkeys(df.columns.copy()[2:])
    df_group = df.query(maj_profile)
    nb_user = df_group["User_ID"].count()
    for parameter in df_results.keys() :
        
       # Retrieve number of votes for each option
        votes = df_group[parameter].value_counts().to_dict()
        for key,val in votes.items() :
            if val == nb_user :
                df_results[parameter] = key
            
    print(df_results)
    
# Average
# df : dataframe we have with the user/group and parameters we are concerned about
# maj_profile : the profiles we apply majority to
def average(df,maj_profile) :
    df_results = dict.fromkeys(df.columns.copy()[2:])
    df_results_rounded = dict.fromkeys(df.columns.copy()[2:])
    df_group = df.query(maj_profile)
    nb_user = df_group["User_ID"].count()
    
    for parameter in df_results.keys() :
        df_results[parameter] = df_group[parameter].mean()
        df_results_rounded[parameter] = math.ceil(df_group[parameter].mean())
    print(df_results)
    print(df_results_rounded)
# Multiplicative in the votes made 
# df : dataframe we have with the user/group and parameters we are concerned about
# maj_profile : the profiles we apply majority to
# mult : dictionary with the key corresponding to the profile and value corresponding to the multiplicative power
def multiplicative(df,maj_profile,mult) :
    df_results = dict.fromkeys(df.columns.copy()[2:])
    df_group = df.query(maj_profile)
    print(df_group)
    for parameter in df_results.keys() :
       # Retrieve number of votes for each option
        votes = df_group[parameter].value_counts().to_dict()
        print(votes)
majority(df_data,"Group == 1 | Group == 2") #df_data["Group"].unique()
majority(df_data,"Group == 1")
unanimity(df_data,"Group == 1 | Group == 2") 

average(df_data,"Group == 1 | Group == 2")
# multiplicative(df_data,"Group == 1 | Group == 2",[])

[1]
[4]
[1]
[1]
{'P1': 1, 'P2': None, 'P3': None, 'P4': 4, 'P5': 1, 'P6': None, 'P7': 1}
[1]
[1]
[1]
{'P1': 1, 'P2': None, 'P3': 1, 'P4': None, 'P5': 1, 'P6': None, 'P7': None}
{'P1': 1, 'P2': None, 'P3': None, 'P4': None, 'P5': None, 'P6': None, 'P7': None}
{'P1': 1.0, 'P2': 2.5, 'P3': 2.5, 'P4': 2.75, 'P5': 2.0, 'P6': 1.5, 'P7': 2.25}
{'P1': 1, 'P2': 3, 'P3': 3, 'P4': 3, 'P5': 2, 'P6': 2, 'P7': 3}

In [6]:
# Borda Count

In [7]:
# Takes as parameters : the parameter (ex:SADD1P1) the profile/group we focus on 
# Return true or false whether we have majority or not
def majority(param,df_profile) : 
    return param > math.ceil(len(df_profile)) / 2

# Return true or false whether we have unanimity or not 
def unanimity(param,df_profile) :
    return param == len(df_profile)

# average of the answers given (but answers are not ordered here) for a parameter
# Could be related to the average of distance we have between the options selected
def average(param,df_profile) :
    return 

# Ranking of alternatives (doing this on all the choices would be too much)
def bordaCount(param,df_profile) :
    return 0

# Setting up multiplication related to profiles
def multiplicative(param,df_profile) :
    return 0

def are_all_options_selected(result_table) :
    for val in result_table.values() :
        if val == None :
            return False
    return True

def get_parameters_left(result_table) :
    parameters_left = []
    for key,val in result_table.items() :
        if val is None : 
            parameters_left.append(key)
    return parameters_left
  
def show_options_selected(result_table) :
    for key,val in result_table.items() :
        if (val is None) :
            print(f"Parameter {key} doesn't have a selected option yet")
        else :
            print(f"Parameter {key}, O{val} was selected")

def check_criterion(result_table,df_users,group_query,condition) :
    if not (are_all_options_selected(result_table)) :
        parameters_name = get_parameters_left(result_table)
        
        df_group = df_users.query(group_query)
        #For each parameter 
        for parameter_name in parameters_name :
                            
            #Get the values for this parameter
            parameter_values = df_group[parameter_name].value_counts()
            for index,param_value in parameter_values.items() :
                
                #Check for majority
                if condition == "majority" :
                    if majority(param_value,df_group):
                        result_table.update({parameter_name : index })
                    
                #Check for unanimity
                elif condition == "unanimity" :
                    if unanimity(param_value,df_group):
                        result_table.update({parameter_name : index })

def remove_linked_parameters(result_table,linked_parameters) :
    keys_to_remove = []
    for lnk_param in linked_parameters :
        for key,val in result_table.items() :
            if lnk_param[0] == key and lnk_param[1] != val :
                keys_to_remove.append(lnk_param[2])
    for key in keys_to_remove :
        print(f"Parameter {key} was removed as its linked parameter option was not selected.")
        result_table.pop(key)

result_table = dict.fromkeys(df_data.columns.copy()[2:])

linked_parameters = [["SADD1P3",3,"SADD1P5"]]

# First set of Resolution Strategies

# Unanimity for Expert and Advanced
check_criterion(result_table,df_data," Group == 1 | Group == 2","unanimity")

# If we still have options to resolve
if not (are_all_options_selected(result_table)) :
    # We apply the second strategy Unanimity for Expert
    check_criterion(result_table,df_data,"Group == 2","unanimity")

show_options_selected(result_table)

Parameter P1, O1 was selected
Parameter P2 doesn't have a selected option yet
Parameter P3, O4 was selected
Parameter P4, O4 was selected
Parameter P5 doesn't have a selected option yet
Parameter P6 doesn't have a selected option yet
Parameter P7 doesn't have a selected option yet

In [8]:
def get_least_vote(threshold,df_data,val) :
    size = df_data[val].unique().size
    serie_opt = df_data[val].value_counts().reindex(range(1,size+1), fill_value=0)
    limit = serie_opt.sum()*threshold
    opt_to_remove = []
    for index, value in serie_opt.items() :
        if (value < limit) :
            opt_to_remove.append(index)
    return opt_to_remove

def remove_least_voted_options(df_data,result_table,threshold) :
    params = get_parameters_left(result_table)
    param_options_to_remove = {}
    for val in params :
        param_options_to_remove.update({val : get_least_vote(threshold,df_data,val)})
        
    return param_options_to_remove

# Reduction of parameters with least votes according to the criterias with a threshold of 15%
p_opt_to_rm = remove_least_voted_options(df_data,result_table,0.15)

print(p_opt_to_rm)

{'P2': [], 'P5': [3], 'P6': [], 'P7': [2]}

In [9]:
# Loading the second questionnaire result
df_data_2 = pd.read_csv("SADD_Options_Selected_2.csv",sep=",")
df_data_2.sort_values(by="Group")

   User_ID  Group  SADD1P2  SADD1P3  SADD1P5
5        9      1        1        3      4.0
6       10      1        1        3      2.0
7        7      1        2        3      2.0
8        8      1        2        3      1.0
9        6      1        2        2      NaN
0       14      2        1        2      NaN
1       15      2        1        2      NaN
2       11      2        1        2      NaN
3       12      2        1        2      NaN
4       13      2        2        3      2.0

In [10]:
# Majority for Expert and Advanced
check_criteria(result_table,df_data_2," Group == 1 | Group == 2","majority")
print(result_table)
if not (are_all_options_selected(result_table)) :
    # Majority for Expert
    check_criteria(result_table,df_data,"Group == 2","majority")
remove_linked_parameters(result_table,linked_parameters)
show_options_selected(result_table)

NameError: name 'check_criteria' is not defined